name: flutter_application_2
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  http: ^1.2.2

  flutter_lints: ^4.0.0

flutter:

  assets:
    - assets/images/head.jpg

  uses-material-design: true